View recipe
AY2021S1-CS2103T-F13-1/tp pull request #47
Opened 2020-10-10 07:22 UTC by khenghun

Enable viewing of all items, all recipes, or a specific item

2020-10-10 07:31 UTC, blackonyyx commented on src/main/java/seedu/address/logic/LogicManager.java
> +
Perhaps some jdocs here would be good to ensure readability of code

2020-10-10 07:32 UTC, blackonyyx commented on src/main/java/seedu/address/logic/Logic.java
> +
Jdocs

2020-10-10 07:36 UTC, blackonyyx commented on src/main/java/seedu/address/logic/commands/ListItemCommand.java
Maybe should have a MESSAGE_USAGE string like if someone does sth like 
listi jkdnkjvsdsn 
or something ( unsure if will return error here)

2020-10-10 07:47 UTC, blackonyyx commented on src/main/java/seedu/address/model/item/DetailedItem.java
> +    public DetailedItem(int id, String name, Quantity quantity, String description, Set<Integer> locationIds,
Constructs ...

2020-10-10 07:50 UTC, blackonyyx commented on src/main/java/seedu/address/model/item/Item.java
> +public class Item extends Inventory {
This doesnt seem to follow OOP design, is there perhaps a better representation?

2020-10-10 07:52 UTC, blackonyyx commented on src/main/java/seedu/address/model/item/Item.java
> +public class Item extends Inventory {
May not be in line with good OOP practices. Consider alternative representation.

2020-10-10 07:52 UTC, aqcd commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +    private class ModelStub implements Model {
import from the file with existing modelstub

2020-10-10 07:52 UTC, aqcd commented on src/main/java/seedu/address/model/Inventory.java
> +public abstract class Inventory {
deceptive naming
try to remove if not too necessary, is an unusual class to have

2020-10-10 08:00 UTC, blackonyyx commented on src/test/java/seedu/address/logic/commands/ViewDetailsCommandTest.java
>          ModelStub modelStub = new ModelStubWithItem(validItem);
Bit more spacing would be good to have and perhaps line commets

2020-10-10 08:00 UTC, blackonyyx commented on src/test/java/seedu/address/model/recipe/IngredientTest.java
> +        ArrayList<Item> itemArrayList = new ArrayList<>();
Same as abv

2020-10-10 08:01 UTC, blackonyyx requested changes
Some Namespace changes should be made especially item extends Inventory

2020-10-10 12:03 UTC, Rahul0506 approved these changes
LGTM

2020-10-10 12:03 UTC, Rahul0506 commented on src/main/java/seedu/address/logic/commands/CommandResult.java
> +import seedu.address.ui.View;
Can you not just import the View.InventoryType ?

2020-10-10 12:03 UTC, Rahul0506 commented on src/main/java/seedu/address/logic/commands/ViewDetailsCommand.java
> +import seedu.address.ui.View;
same as before

2020-10-10 12:03 UTC, Rahul0506 commented on src/main/java/seedu/address/model/recipe/Ingredient.java
> +        HashMap<Integer, String> hm = new HashMap<>();
maybe use a more descriptive name

2020-10-11 14:58 UTC, aqcd commented on src/main/java/seedu/address/logic/commands/ListItemCommand.java
> +        if (model.getFilteredItemList().size() == 0) {
use isEmpty

2020-10-11 14:58 UTC, aqcd commented on src/main/java/seedu/address/logic/commands/ListRecipeCommand.java
> +            + "will you like to add some?";
Might be better to not have "will you like to add some?" if there's no direct button to do so

2020-10-11 14:58 UTC, aqcd commented on src/main/java/seedu/address/logic/commands/ListRecipeCommand.java
> +        if (model.getFilteredRecipeList().size() == 0) {
use isEmpty

2020-10-11 14:58 UTC, aqcd commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +package seedu.address.logic.commands;
should this file be added?

2020-10-12 04:22 UTC, aqcd approved these changes

2020-10-12 08:00 UTC, merged