update UG - jinglin
AY2021S1-CS2103T-F13-1/tp pull request #72
Opened 2020-10-18 08:27 UTC by aqcd

resolves #55

2020-10-19 01:07 UTC, blackonyyx requested changes
Some minor inaccuracies in Sequence Diagram need to be addressed

Overall format looks good.

Am not sure whether we need to express Exception Handling steps in Sequence flow diagrams. 

Can consider looking at this if you would like to do so. (Optional)
https://johanvergeer.github.io/posts/uml-sequence-diagram-exception-handling

2020-10-19 01:07 UTC, blackonyyx commented on docs/diagrams/sequenceDiagrams/AddQuantityToItemCommandSequenceDiagram.puml
> +InventoryinatorParser -> AddQuantityToItemCommandParser : parse("addq -n banana -q 50")
Command Word is removed at this step, the input that is recieved by parser is `-n banana -q 50`

2020-10-19 01:07 UTC, blackonyyx commented on docs/diagrams/sequenceDiagrams/AddQuantityToItemCommandSequenceDiagram.puml
> +[<--LogicManager
Command Result is Returned and parsed to the UI i think So its not destroyed

<img width="854" alt="Screenshot 2020-10-19 at 9 00 17 AM" src="https://user-images.githubusercontent.com/35429757/96390978-a5b3ac80-11e9-11eb-9fea-a92b866ef24f.png">

2020-10-19 01:07 UTC, blackonyyx commented on docs/diagrams/sequenceDiagrams/AddQuantityToItemCommandSequenceDiagram.puml
> +deactivate EditItemCommand
EditItem Command should also probably be destroyed after CommandResult is returned.

2020-10-19 05:45 UTC, aqcd commented
Opened #73 regarding above comment

2020-10-20 13:26 UTC, blackonyyx approved these changes
LGTM after adding the one additional destroy mentioned.

2020-10-20 13:26 UTC, blackonyyx commented on docs/diagrams/sequenceDiagrams/AddQuantityToItemCommandSequenceDiagram.puml
> +
AddQuantityToItemCommand should also similarly be destroyed.

2020-10-20 13:38 UTC, merged